# Generated by Django 5.0.8 on 2024-08-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
    ]
